name: Maven Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile and Test with Maven
        run: mvn clean verify

      - name: Upload JUnit Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: '**/target/surefire-reports/TEST-*.xml'

      - name: Build Docker Image
        run: docker build -t my-java-app .

      - name: Install Grype
        run: |
          mkdir -p ./bin
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b ./bin
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Add Grype Ignore File
        run: |
          echo "CVE-2023-12345" > .grypeignore
          echo "CVE-2022-99999" >> .grypeignore
        shell: bash

      # ✨ Output full vulnerability report (non-blocking)
      - name: Generate Grype Report (JSON)
        run: grype my-java-app:latest -o json > grype-report.json

      - name: Upload Grype Report
        uses: actions/upload-artifact@v4
        with:
          name: grype-report
          path: grype-report.json

      # ✅ Blocking scan with ignore file
      - name: Scan Docker Image with Grype
        run: grype my-java-app:latest --fail-on critical --file .grypeignore
