name: Maven Build  

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Compile and Test with Maven
        run: mvn clean verify

      - name: SonarCloud Scan (Using GitHub Action)
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: |
            -Dsonar.projectKey=kashishrastogi03_major_assignment
            -Dsonar.organization=kashishrastogi03
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload JUnit Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: '**/target/surefire-reports/TEST-*.xml'
